name: remote test__push listener

on: 
  push:
  repository_dispatch:

jobs:
  signals2:
    runs-on:  ubuntu-latest
    steps:
      - name: receive repository_dispatch
        if: github.event.action == 'send_message'
        run: |
          echo "repository_dispatch"
      - name: push
        if: github.event.action != 'send_message'
        run: |
          echo "push"